image: 172.16.1.22:5000/laravel-dock:php-fpm

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

codestyle:
  stage: test
  cache: {}
  script:
    - phpcs --standard=PSR2 --extensions=php app

phpunit:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate --env=testing
    - vendor/bin/phpunit --coverage-text --colors=never
